### ISSUE TITLE
rename participation type in create event form

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#452] opened 2018-01-28 20:56 UTC
Rename the labels to "Teams" and "Einzel"

![image](https://user-images.githubusercontent.com/29160369/35486933-cee8af8a-0475-11e8-9fe9-e61edb234c85.png)

consider combining this with #451

**Comment by GittiHab** [comment] 2018-01-30 17:29
Duplicate of #469

**Closed as completed by GittiHab** 2018-01-30 17:29 UTC
Labels: team bruteforce, epic create event, priority medium
