### ISSUE TITLE
Username is displayed incorrectly

### ISSUE THREAD

**Issue by emanuel-metzenthin** [hpi-swt2/sport-portal#205] opened 2017-12-05 13:53 UTC
I don't think that this hash belongs there.

![image](https://user-images.githubusercontent.com/18703652/33610488-f9c1d03a-d9cb-11e7-8fef-31a247b17e5e.png)

**Comment by jkbe** [comment] 2017-12-06 10:11
@hpi-swt2/scrum-masters do you know who worked on this lately?

**Comment by jkbe** [comment] 2017-12-08 08:41
@hpi-swt2/product-owner please take a look and schedule for next sprint. Thanks!

**Comment by fpottbaecker** [comment] 2017-12-09 12:54
1. Why was i assigned to this issue?
2. I could not reproduce this issue locally, on dev or master.

**Comment by GittiHab** [comment] 2018-01-02 16:43
This does not seem to be relevant anymore. Should it occur again, please write down how to reproduce and reopen this issue.

**Closed as completed by GittiHab** 2018-01-02 16:43 UTC
Labels: bug
